"""Chapter checkpoints: executable inputs and pointers into real source files."""

LESSONS = {
    "C0": {
        "title": "从资料到可追溯对象", "chapter": 15, "panel": "resources", "role": "developer",
        "why": "先找到一份政策和一个代码函数，核对它们怎样获得身份、版本与来源。",
        "build": "先阅读 raw/manifest.json 的来源声明，再实现 parse_source 和 compile_documents。返回的对象将成为后面检索和建模的共同输入。",
        "expect": "展开订单取消规则和退款消费者，核对正文、版本、ACL、source 与 lineage。源码以 Python AST 提取；不是固定长度切块。",
        "failure": "切换 support 后重新读取。代码对象不应出现；不能只在页面隐藏而仍从接口返回。",
        "request": {"op": "resources"},
        "sources": [("build_baseline.py", "parse_source"), ("build_baseline.py", "compile_documents"),
                    ("../data/raw/manifest.json", None), ("../data/raw/business/order-cancellation.md", None)],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_build_baseline.py -v",
    },
    "C1": {
        "title": "先检查权限，再检索", "chapter": 15, "panel": "search", "role": "developer",
        "why": "搜索之前先确定谁可以使用哪些对象，相关性分数才有意义。",
        "build": "在 C0 的对象上增加候选过滤和 BM25。页面默认关闭语义代理，先检查词法通道；接下来 C2 再组合通道。",
        "expect": "搜索 handle_order_cancelled，开发者能找到退款消费者；查看证据卡上的引用和通道。",
        "failure": "切换 support，以同一问题重试，结果中不能有代码引用。",
        "request": {"op": "search", "question": "handle_order_cancelled", "disabled_channels": ["semantic_proxy"]},
        "sources": [("northstar.py", "NorthstarPlatform.search"), ("retrieval.py", "bm25")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_northstar.py -v",
    },
    "C2": {
        "title": "通道组合与历史时间", "chapter": 15, "panel": "search", "role": "developer",
        "why": "同一个问题可能用业务语言或代码符号表达；同一条政策也可能有不同时间版本。",
        "build": "增加离线语义代理与 RRF 合并，再把业务有效时间和平台已知时间传入候选过滤。代理使用同义词与 Jaccard，不调用嵌入模型。",
        "expect": "比较单通道与组合结果；填写历史时间后，核对命中政策的版本和适用时间。",
        "failure": "关闭全部通道应得到空证据，而不是偷偷返回预录结果。把已知时间提前到入库前，相应材料不能被使用。",
        "request": {"op": "search", "question": "取消事件有哪些 consumer 影响", "disabled_channels": []},
        "sources": [("retrieval.py", "reciprocal_rank_fusion"), ("northstar.py", "NorthstarPlatform.documents_as_of")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_review_regressions.py -v",
    },
    "C3": {
        "title": "让类型和关系有可检查的含义", "chapter": 16, "panel": "model", "role": "developer",
        "why": "检索到事件和代码还不够，需要说明什么叫消费事件、什么证据支持这条关系。",
        "build": "按能力问题、术语、概念和源映射四份输入编译模型，再用对象与关系验证。页面返回当前角色可见对象所需的模型切片。",
        "expect": "查看 EventSchema、CodeSymbol 和 CONSUMED_BY 的定义，再对照下面的实例关系。",
        "failure": "在本地修改概念模型中一条关系的端点类型，再运行下面的测试；错误模型应在平台启动时被拒绝。",
        "request": {"op": "model"},
        "sources": [("modeling.py", "compile_domain_model"), ("modeling.py", "semantic_slice"),
                    ("../data/modeling/competency-questions.json", None), ("../data/modeling/glossary.json", None),
                    ("../data/modeling/concept-model.json", None), ("../data/modeling/source-mappings.json", None)],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_modeling.py -v",
    },
    "C4": {
        "title": "沿关系查证，生成可读视图", "chapter": 16, "panel": "trace", "role": "developer",
        "why": "从一个事件找到消费者，再到测试；每条关系的方向和依据都要可检查。",
        "build": "在经过验证的对象上加入有界遍历。再用同一批可见对象生成 Wiki，避免产生第二套事实。可在操作选择框切换关系、Wiki 和架构核对。",
        "expect": "从 event-order-cancelled 出发，看见三个消费者及各自测试；切换 Wiki 查看输入引用。",
        "failure": "support 不应沿同一事件读到代码；架构声明与证据不一致时，核对结果保留差异。",
        "request": {"op": "trace", "seed": "event-order-cancelled"},
        "sources": [("knowledge_views.py", "trace_dependency"), ("knowledge_views.py", "build_role_scoped_wiki")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_architecture_consistency.py -v",
    },
    "update": {
        "title": "修改政策，看变化怎样传下去", "chapter": 16, "panel": "update", "role": "product",
        "why": "一次成功的查询不能说明系统可以持续使用；来源变化后，视图和任务也必须作出反应。",
        "build": "在当前实验空间的政策副本中追加一条说明，重新编译资源与 Wiki，再把旧任务标为需要重新取证。源码中的原始 fixture 不会被改写。",
        "expect": "版本增加 lab 后缀，Manifest 改变，检索与 Wiki 包含新说明。原有任务保存旧快照，但显示资源已更新。",
        "failure": "先准备并批准一次动作，再更新政策。回到 SRE 后，旧批准不能执行，需要新建事故任务重新诊断。",
        "request": {"op": "policy.update", "note": "新增核验说明：checkpointalpha"},
        "sources": [("workbench.py", "Workspace.update_policy"), ("workbench.py", "Workspace._build")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_workbench.py -v",
    },
    "C5": {
        "title": "从任务条件组装本次上下文", "chapter": 17, "panel": "tasks", "role": "developer", "scenario": "change",
        "why": "共享资源说明企业有什么，任务记录说明这次要做什么、用了哪些依据、还缺什么。",
        "build": "先保存任务条件，再调用 context；把本次材料作为不可覆盖的快照保存，将后续笔记写成有主体的任务事件。",
        "expect": "创建变更任务并构造上下文。任务条件、证据、关系、缺口和工作记录分别可见；刷新页面后仍能继续。",
        "failure": "换成 support 后不能读取开发者的任务。用户笔记标为未核实声明，不自动变成企业事实。",
        "sources": [("workbench.py", "Workspace.create_task"), ("workbench.py", "Workspace.context"), ("northstar.py", "NorthstarPlatform.context")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_workbench.py -v",
    },
    "C6": {
        "title": "走完预览、批准、执行与验证", "chapter": 17, "panel": "tasks", "role": "sre", "scenario": "incident",
        "why": "一份上下文不会自动赋予修改业务的权力。具体动作要经过独立检查。",
        "build": "复用核心动作状态机，通过服务保存预览、批准、回执和模拟队列；每次请求在 SQLite 事务中完成读取、检查、变更和保存。",
        "expect": "SRE 创建任务、构造上下文、准备动作；切换事故负责人检查参数并批准；回到 SRE 执行和验证。队列应从842降到742。",
        "failure": "推进教学时钟61秒后尝试批准或执行，应拒绝过期请求。另建空间验证拒绝分支与重复执行分支。",
        "sources": [("northstar.py", "NorthstarPlatform.prepare_replay"), ("northstar.py", "NorthstarPlatform.execute_replay"), ("workbench.py", "WorkspaceStore.call")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_workbench.py -v",
    },
    "C7": {
        "title": "从企业结构进入经营分析", "chapter": 17, "panel": "tasks", "role": "executive", "scenario": "strategy",
        "why": "销售变化要放回目标、能力、组织、应用和数据中解释，先确认指标，再读取可比较事实。",
        "build": "沿用任务记录和快照机制，将战略模式接入同一个 context 入口；确认动作绑定完整指标定义和数据快照。",
        "expect": "先看到待确认的指标契约。确认后再次构造上下文，核对1200到840的差异、目标差距、四种独立分解及证据缺口。",
        "failure": "未确认口径不能计算；有数值差异也不能据此把候选关联写成已证实根因。复核记录只表示人工复核，不会改经营目标。",
        "sources": [("strategy.py", "StrategicContext.definition_confirmation"), ("strategy.py", "StrategicContext.package"), ("workbench.py", "Workspace.context")],
        "test": "python3 -m unittest discover -s examples/enterprise-case/tests -p test_strategy.py -v",
    },
}
